---
title: "mapas"
output: html_document
date: '2022-11-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Mapas

#LINKS DE INTERES

https://wms.ign.gob.ar/geoserver/web/?wicket-crypt=o7-m5S_KIHY

https://rpubs.com/Pa-VD/650673

https://rpubs.com/angiescetta/info-osmdata

https://cengel.github.io/R-spatial/

https://rstudio-pubs-static.s3.amazonaws.com/983953_9c54293eeb434e5ea3ceb7e36717eb14.html#21_Acceso_a_los_datos

https://datos.gob.ar/dataset/jgm-servicio-normalizacion-datos-geograficos/archivo/jgm_8.27

https://github.com/pablotis/capas-shapefiles/tree/master/GBA_3_cordones

https://rpubs.com/danielricardogm/BAendatos_genero

https://rstudio-pubs-static.s3.amazonaws.com/649640_203b6656cf78468382eaa80d2f78177f.html



```{r warning=FALSE}


rm(list = ls())

# install.packages("ggmap")
# install.packages("readr")
# install.packages("sf")
# install.packages("sp")
# install.packages("RColorBrewer")
# install.packages("osmdata")
# install.packages("leaflet")
# install.packages("ggsn")
# install.packages("kableExtra")
# install.packages("osmextract")

library(tidyverse)
library(ggmap)
library(readr)
library(sf)
library(sp)
library(RColorBrewer)
library(osmdata)
library(leaflet)
library(ggsn)
library(kableExtra)
library(osmextract)



```

```{r warning=FALSE}

setwd("G:/Mi unidad/R/Proyectos/GIS (Tesis)/")

#partidos <- st_read("Codgeo_Pais_x_dpto_con_datos/pxdptodatosok.shp")

partidos2 <- st_read("G:/Mi unidad/R/Proyectos/GIS (Tesis)/Partidos/limite_partidos/Limite_partidos/Shapefile") #https://catalogo.datos.gba.gob.ar/dataset/partidos/archivo/6cd47ea4-37af-4fdb-9d38-678c1067b7e9


# temp_shapefile <- tempfile()
# download.file("https://infra.datos.gob.ar/catalog/modernizacion/dataset/7/distribution/7.35/download/departamentos.zip", temp_shapefile)
# unzip(temp_shapefile)
# partidos <- st_read('departamentos/departamentos.shp')

#trenes <- st_read("https://datos.transporte.gob.ar/dataset/8a83da77-e431-4d6f-a14a-c98ebc0b900b/resource/624f34de-faa7-4657-8f0a-0aed482f2341/download/estaciones_estaciones.csv", options = "ENCODING=UTF-8")

estacion_trenes <- st_read('wfs:https://wms.ign.gob.ar/geoserver/ows?service=wfs&version=1.1.0&request=GetCapabilities','ign:puntos_de_transporte_ferroviario_AN070') %>%
  filter(gna=='Estación'|gna=='EStación') %>%
   select(fna,gna,nam)

lineas_trenes <- st_read('wfs:https://wms.ign.gob.ar/geoserver/ows?service=wfs&version=1.1.0&request=GetCapabilities','ign:lineas_de_transporte_ferroviario_AN010') %>%
   select(fna)

bp <- st_read("https://datosabiertos.desarrollosocial.gob.ar/dataset/0d022767-9390-486a-bff4-ba53b85d730e/resource/0396a8a3-8998-4fc1-8503-e6706667b5fa/download/2022-07-13_info_publica.gpkg") 




lineas_trenes2 <- st_read("https://wms.ign.gob.ar/geoserver/transporte/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=transporte%3Alineas_de_transporte_ferroviario_AN010&maxFeatures=50&outputFormat=application%2Fjson")


```

```{r}

#delimitamos areas de estudio


area_estudio <- c('Merlo',
         'Morón',
         'Moreno',
         'Quilmes',
         'José C. Paz',
         'Ituzaingó',
         'Lanús',
         'La Matanza',
         'Lomas de Zamora',
         'Malvinas Argentinas',
         'San Miguel',
         'San Isidro',
         'Tigre',
         'Vicente López',
         'Tres de Febrero',
         'Almirante Brown',
         'Esteban Echeverría',
         'Florencio Varela',
         'Ezeiza',
         'Hurlingham',
         'General San Martín',
         'Berazategui',
         'Avellaneda',
         'San Fernando'
        
         )




AMBA <- partidos2 %>% 
  filter(nam %in% area_estudio) %>% 
  #select(NAM)%>%
  mutate(Zona = case_when(nam %in% c('Avellaneda','Quilmes','Berazategui','Florencio Varela','Almirante Brown') ~ 'Zona del Sureste',
                          nam %in% c('Presidente Perón','Esteban Echeverría','Ezeiza') ~ 'Zona del Sur',
                          nam %in% c('Lanús','Lomas de Zamora','La Matanza') ~ 'Zona Sur Oeste',
                          nam %in% c('Vicente López','San Isidro','San Fernando', 'Tigre') ~ 'Zona Noreste',
                          nam %in% c('Merlo','Moreno') ~ 'Zona Noroeste',
                          nam %in% c('General San Martín','Tres de Febrero','San Miguel', 'Malvinas Argentinas', 'José C. Paz') ~ 'Zona Norte Centro',
                          nam %in% c('Morón','Hurlingham','Ituzaingó') ~ 'Zona Oeste',
                          )) 

# CABA <- partidos2 %>%
#   filter(provincia == "Ciudad Autónoma de Buenos Aires") %>%
#   select(departamen) %>%
#   st_union() %>% #une todos los poligonos (comunas) para que solo se vea caba
#   st_as_sf(crs = 4326)
# 
# union_AMBA <- AMBA %>%
# st_union()




```

```{r, fig.width=10, fig.height=9}

#MAPA CON 

ggplot() +
  geom_sf(data = AMBA)

# #NOMBRES ARREGLADOS, 
# FALTA CABA Y 
# CHEQUEAR MUNICIPIOS (hecho)

```


```{r, fig.width=10, fig.height=9}

#MAPA CON BARRIOS POPULARES

#VAMOS A PROBAR FILTRAR POR UNA ZONA (ZONA DEL SUR)"


# bp <- bp %>% 
#   rename(geometry = geom)

BP_AMBA <-bp %>% 
  mutate(departamento = case_when(departamento == "José M. Ezeiza"~"Ezeiza",
                            TRUE ~ departamento )) %>% 
  filter(departamento %in% area_estudio) %>% 
  filter(provincia == "Buenos Aires") 


ggplot() +
  geom_sf(data = AMBA , color='black', aes(fill = Zona),  size = 0.1)+
  scale_fill_manual(values=c("#e74645", "#fb7756","#facd60","#fdfa66","#1ac0c6","#e69645","#45e645"))+
  geom_sf_text(data = AMBA , aes(label=nam),size=2, alpha=0.8, colour='black')+
  geom_sf(data = BP_AMBA, color='black',   size = 0.1)+
  #facet_wrap(~Zona)+ VER COMO HACER PARA QUE QUEDE GRANDE
          theme_bw()

```

```{r, fig.width=10, fig.height=9}

#Vamos a probar mapa con trenes

BP_AMBA <-bp %>% 
  mutate(departamento = case_when(departamento == "José M. Ezeiza"~"Ezeiza",
                            TRUE ~ departamento )) %>% 
  filter(departamento %in% area_estudio) %>% 
  filter(provincia == "Buenos Aires") 

lineas_trenes <- lineas_trenes %>%
  st_as_sf(crs = 4326)

lineas_trenes2 <- lineas_trenes %>% st_transform(st_crs(AMBA))
lineas_trenes_AMBA <- st_intersection(lineas_trenes2,AMBA)

estacion_trenes2 <- estacion_trenes %>% st_transform(st_crs(AMBA))

estacion_trenes_AMBA <- st_intersection(estacion_trenes2,AMBA)

ggplot() +
  geom_sf(data = AMBA , color='black', fill = 'lightcyan',  size = 0.2, alpha = 0.5)+
  # scale_fill_manual(values=c("#e74645", "#fb7756","#facd60","#fdfa66","#1ac0c6","#e69645","#45e645"))+
  geom_sf_text(data = AMBA , aes(label=nam),size=2, alpha=0.8, colour='black')+
  geom_sf(data = BP_AMBA, color='black',   size = 0.1)+
  geom_sf(data=lineas_trenes_AMBA, size=0.4, aes(color='Lineas de FF.CC'),show.legend = 'line',alpha=0.2)+
  geom_sf(data=estacion_trenes_AMBA, size=0.4, aes(color='Estaciones de FF.CC'),show.legend = 'point',alpha=0.7)+
   labs(title = 'Área Metropolitana de Buenos Aires (AMBA)',
       subtitle = 'Infraestructura de Transporte Ferroviario',
       caption= 'Fuente: OSM | INDEC | IGN',
       y="Latitud ",
       x="Longitud")+
  scale_color_manual(values= c('Estaciones de FF.CC'='black', 'Lineas de FF.CC'='red'),
                     name='Referencias',
                      guide = guide_legend(override.aes = list(linetype = c('blank',"solid"),
                                                               size=c('Estaciones de FF.CC'=3,
                                                                      'Lineas de FF.CC'=1),
                                                               shape = c(20, NA),
                                                               alpha = 1)))+
scalebar(data=AMBA, dist = 6, st.size=2.5, height=0.01, dist_unit = "km",  transform = T, location="bottomright" , model = 'WGS84',border.size=0.5)+
   north(AMBA,
         symbol = 16, 
         scale=0.08)+
          theme_bw()
  
  
  
  
       
#########NO PUEDO HACER INTESECTION ENTRE AMBA Y LINEAS DE TRENES (LO RESOLVI CON ST TRANSFORM CAMBIANDO EL CRS DE LINEAS TRENES)

```

PROBAMOS DATOS DE OSM
https://rstudio-pubs-static.s3.amazonaws.com/983953_9c54293eeb434e5ea3ceb7e36717eb14.html#21_Acceso_a_los_datos

```{r}

library(maptools)
#BARRIOS POPULARES

barrios_pop <- st_read("https://datosabiertos.desarrollosocial.gob.ar/dataset/0d022767-9390-486a-bff4-ba53b85d730e/resource/97cc7d10-ad4c-46cb-9ee4-becb402adf9f/download/2022-07-13_info_publica.geojson")

#BARRIOS POPULARES SOLO CABA

barrios_pop <- barrios_pop %>% filter(provincia=="Ciudad Autónoma de Buenos Aires")

#POLIGONO BARRIOS

barrios <- read_sf("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/barrios/barrios.geojson")


#extraemos el perímertro de la ciudad
bbox_ba <- getbb("Capital Federal, Buenos Aires, Argentina")
mapa_ba <- get_stamenmap(bbox_ba,  zoom = 12)

polygon_ba <- getbb("Capital Federal, Buenos Aires, Argentina", format_out = "sf_polygon")
polygon_ba <- polygon_ba$multipolygon

##############################################GBA######################################
#extraemos el perímertro de la gba
bbox_gba <- getbb("Avellaneda, Buenos Aires, Argentina")
mapa_gba <- get_stamenmap(bbox_gba,  zoom = 12)

polygon_gba <- getbb("Avellaneda, Buenos Aires, Argentina", format_out = "sf_polygon")
polygon_gba <- polygon_gba$multipolygon
#######################################################################################



paradas_ba <- opq(bbox_ba) %>%
                    add_osm_feature(key = "public_transport", value = "stop_position")

#extraemos los puntos
paradas_ba  <- osmdata_sf(paradas_ba)
paradas_ba   <- paradas_ba$osm_points


#Filtrado de parques dentro de la ciudad
paradas_ba_b <- st_intersection(paradas_ba,polygon_ba$geometry)

```

```{r}
ggmap(mapa_ba)




```


